# Generated by Django 3.1.7 on 2021-03-09 22:19

import bioinformatica.models.fast5
import bioinformatica.models.fastQ
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Client name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinformatica.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DynamicAttributeDefinition',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dynamicAttributeDef_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=120)),
                ('attribute_description', models.TextField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('experiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('place', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=120)),
                ('executionCommands', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FastQ',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fastQ_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('responsible', models.CharField(max_length=120, verbose_name='Responsible')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinformatica.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 3, 9, 19, 19, 10, 825515), verbose_name='Create date')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioinformatica.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FastQFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(help_text='Seleccione El archivo FastQ', upload_to=bioinformatica.models.fastQ.get_upload_path, verbose_name='Load fastQ File')),
                ('fastQ', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioinformatica.fastq')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fastq',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinformatica.sample'),
        ),
        migrations.CreateModel(
            name='Fast5',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fast5_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('file', models.FileField(blank=True, help_text='Seleccione El archivo Fast5', null=True, upload_to=bioinformatica.models.fast5.get_upload_path, verbose_name='Load fast5 File')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinformatica.sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bioinformatica.project'),
        ),
        migrations.CreateModel(
            name='DynamicAttributeInstance',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dynamicAttributeInst_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_value', models.CharField(max_length=120)),
                ('attribute_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioinformatica.dynamicattributedefinition')),
                ('experiment_attributes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioinformatica.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
